To Do List
username-forGithub/To-Do-List pull request #2
Opened 2022-08-10 14:11 UTC by username-forGithub

In this part of the project adding and removing functionalities have been added.

2022-08-10 14:58 UTC, 1GORDON requested changes
##
## Hi @username-forGithub ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️
- Professional readme ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] Kindly format your readme file correctly. 
![readme](https://user-images.githubusercontent.com/63917725/183934101-13b5205f-40ff-471f-b7b3-bc6168b25503.PNG)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-10 14:58 UTC, 1GORDON commented on modules/create.js
>  }
Great design @username-forGithub 🤝

- [ ] As specified in project requirements, you are supposed to use ES6 syntax in your Javascript files. Kindly format your module functions and methods in the `create`, `delete`, and `update` files to ES6 syntax.

2022-08-10 14:58 UTC, 1GORDON commented on modules/create.js
> -// localStorage.removeItem('arrStored')
Great job @username-forGithub 🤝

- [ ] As specified in the project requirements, kindly make sure your data is saved in the local storage.

2022-08-10 14:58 UTC, 1GORDON commented on modules/create.js
>  }
Great job @username-forGithub 🤝

- [ ] As specified in the project requirements, kindly Implement a function for editing task descriptions correctly. I can't seem to edit the tasks on your design

2022-08-10 15:08 UTC, username-forGithub commented
Hi


On Wed, Aug 10, 2022 at 7:58 PM Gordon Tinyefuza ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> Hi @username-forGithub <https://github.com/username-forGithub> ✋
>
> Good job so far!
> Highlights!
>
>    - Followed Gitflow ✔️
>    - Good commit messages ✔️
>    - Linters are passing ✔️
>    - Descriptive Pull request ✔️
>    - Professional readme ✔️
>
> Hello ✋, you have done well reaching this point of the milestone 🤝 . But
> there are some issues that you still need to work on to go to the next
> project but you are almost there!
> Status: Required Changes ♻️⛔️
>
>    - Kindly format your readme file correctly.
>    [image: readme]
>    <https://user-images.githubusercontent.com/63917725/183934101-13b5205f-40ff-471f-b7b3-bc6168b25503.PNG>
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread and tag me
> @1GORDON if something is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In modules/create.js
> <https://github.com/username-forGithub/To-Do-List/pull/2#discussion_r942545331>
> :
>
> >    updateStorege(arr);
>
>    show();
>
>  }
>
>
> Great design @username-forGithub <https://github.com/username-forGithub>
> 🤝
>
>    - As specified in project requirements, you are supposed to use ES6
>    syntax in your Javascript files. Kindly format your module functions and
>    methods in the create, delete, and update files to ES6 syntax.
>
> ------------------------------
>
> In modules/create.js
> <https://github.com/username-forGithub/To-Do-List/pull/2#discussion_r942556385>
> :
>
> > -// localStorage.removeItem('flag')
>
> -// localStorage.removeItem('arrStored')
>
>
> Great job @username-forGithub <https://github.com/username-forGithub> 🤝
>
>    - As specified in the project requirements, kindly make sure your data
>    is saved in the local storage.
>
> ------------------------------
>
> In modules/create.js
> <https://github.com/username-forGithub/To-Do-List/pull/2#discussion_r942559152>
> :
>
> >    updateStorege(arr);
>
>    show();
>
>  }
>
>
> Great job @username-forGithub <https://github.com/username-forGithub> 🤝
>
>    - As specified in the project requirements, kindly Implement a
>    function for editing task descriptions correctly. I can't seem to edit the
>    tasks on your design
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/username-forGithub/To-Do-List/pull/2#pullrequestreview-1068422761>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AY3ODIRWKJ2ZEPKWUBI3SLTVYO7RHANCNFSM56EWGDVQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-11 04:30 UTC, Kingstalux approved these changes
Hi @username-forGithub,
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
![68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966](https://user-images.githubusercontent.com/85113567/184064312-13fe7b34-10de-4611-8928-4b634156ac19.gif)

## Highlights :clap: 
:ballot_box_with_check: Books can be added, edited and deleted :fire: 
:ballot_box_with_check: Good job using ES6 syntax :+1: 
:ballot_box_with_check: Professional README file :100: 

Good job implementing the required changes :+1: Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] (OPTIONAL) Kindly remove all hardcoded array elements so that new tasks will only be added from your site :+1: 
- [ ] (OPTIONAL) Also the value of your index should start from 1 and not 0 as stated in the requirements. Kindly rectify this issue :smile: 
- [ ] (OPTIONAL) Make sure the value of the indexes of the remaining elements are updated after one element is deleted. For example, if you have 2 tasks on your list, if the first task is deleted. then the index of the second task should be updated to 1 :+1: 
- [ ] (OPTIONAL) Finally , try to implement your functionality according to the given [video](https://www.youtube.com/watch?v=AcUd-_Yjjqg). Notice that to delete an element, the user clicks on the 3 dots and the delete icon appears. It would be great if your site functions exactly like that :100: 

_These are all mandatory requirements but as they were not pointed out in your first review, I'll leave them as optional but I strongly suggest you implement the various functionalities_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 04:42 UTC, merged